---

- include: install-centos-6.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '6'

- include: install-centos-7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'

- name: Check if /root/.my.cnf already exists
  stat:
    path: '/root/.my.cnf'
  register: my_cnf

- name: Generate password
  set_fact:
    mysql_password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters') }}"
  when: not my_cnf.stat.exists

- name: Set MariaDB password in /root/.my.cnf
  template:
    src: 'my.cnf.j2'
    dest: '/root/.my.cnf'
    mode: 0600
    owner: root
    group: root
  when: not my_cnf.stat.exists

- name: Set MariaDB root password
  mysql_user:
    user: 'root'
    password: '{{ mysql_password }}'
  when: not my_cnf.stat.exists

- name: Remove MariaDB 'test' database
  mysql_db:
    name: 'test'
    state: absent

- name: Set up /etc/my.cnf.d/server.cnf
  template:
    src: 'server.cnf.j2'
    dest: '/etc/my.cnf.d/server.cnf'
    mode: 0644
    owner: root
    group: root
  notify: Restart MariaDB
