---

- include: install-centos-6.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '6'

- include: install-centos-7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'
